### PR TITLE
Include some packages which are not actually zope.app packages.

### PR DESCRIPTION
**Pull request by icemac**
These packages can be used resp. are used in Zope 3 and Bluebream (aka Zope 3), so it would be nice to test and version them here.

### CODE REVIEW

**Comment by jamadden** [comment]
`zope.app.wsgi` is not compatible with PyPy. It [writes to files without closing them](https://github.com/zopefoundation/zope.app.wsgi/blob/master/src/zope/app/wsgi/README.txt#L146), assuming the GC will clean them up, leading to the test failures.

**Comment by mauritsvanrees** [comment]
I don't think this is a good place to put `zope.app` packages. They used to be in `zopeapp-versions.cfg`, but that file does not exist anymore. It's in the [1.1.6 tag](https://github.com/zopefoundation/zopetoolkit/blob/1.1.6/zopeapp-versions.cfg).

**Comment by hannosch** [comment]
We removed all zope.app packages from the ZTK on purpose. I don't see what changed as to revert that decision.

**Comment by icemac** [comment]
I'd like to add the those zope.app packages which are not so specific for the Zope 3 app server.
I thought str least some of them are used by Zope 2. But looking at the transitive dependencies of Zope 2 showed me that I was wrong.

**Pull request closed without merging**
