### PR TITLE
Support PyPy3

### PR DESCRIPTION
**Pull request by icemac**
Try out the status of the PyPy3 support of the ZTK packages.

### CODE REVIEW

**Comment by mgedmin** [comment]
Interesting to see zope.sendmail failing on both PyPy and PyPy3 while https://travis-ci.org/zopefoundation/zope.sendmail shows both as passing.

Flaky tests that don't always fail?

**Comment by mgedmin** [comment]
Also, it looks like the pypy3 job actually runs pypy2?

**Comment by icemac** [comment]
@mgedmin It seems to be a flaky test. Here is an example where only CPython 2.7 fails but both PyPy versions are fine: https://travis-ci.org/zopefoundation/zopetoolkit/builds/283726779

**Comment by mgedmin** [comment]
Filed https://github.com/zopefoundation/zope.sendmail/issues/15.

**Pull request merged**
