### PR TITLE
Try out 3.7 support of the packages.

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
Cool, only `zope.cachedescriptors` breaks because of a changed doc string in Python 3.7.

**Comment by tseaver** [comment]
> Cool, only zope.cachedescriptors breaks because of a changed doc string in Python 3.7.

What a silly assertion, even for doctests!

**Comment by icemac** [comment]
> What a silly assertion, even for doctests!

No problem, we are here to fix the assertions of the past. :-)

**Comment by serhiy-storchaka** [comment]
The more reliable way of writing this doctest:
```
>>> p.radius.__doc__ == float.__doc__
True
```
But maybe actually it should test the type of `p.radius`?
```
>>> isinstance(p.radius, float)
True
```

**Pull request merged**
