### PR TITLE
Update version pins (PyPy).

### PR DESCRIPTION
**Pull request by jamadden**
@mgedmin [noticed](https://mail.zope.org/pipermail/zope-dev/2015-May/046765.html) that the ZTK builds were failing. This was because `zope.container` among others need `persistent` 4.1.0 or later to support PyPy, but the version pin here was too old.

This updates that version pin and several other versions that are needed for PyPy support. 

Unfortunately, I can't add PyPy to `.travis.yml`; when I locally try to run `bin/test-ztk` under PyPy, I get ten test failures:

```
10 failure(s).
- test-ztk-zope.catalog
- test-ztk-zope.component
- test-ztk-zope.container
- test-ztk-zope.pagetemplate
- test-ztk-zope.pluggableauth
- test-ztk-zope.publisher
- test-ztk-zope.security
- test-ztk-zope.session
- test-ztk-zope.testing
- test-ztk-zope.testrunner
```

A few of those may be due to having an older ZODB (I didn't update its pin because it's currently at 4.2.0.b1, not final), but several of them are legitimate PyPy (or PURE_PYTHON) compatibility issues.  I can try to take a look at the ten projects and create PRs as needed.

### CODE REVIEW

**Comment by tseaver** [comment]
Feel free to update the ZODB pin for the ZTK trunk to a beta version:  we've often had pre-releases pinned in the past.

**Comment by jamadden** [comment]
Thanks. That fixed `zope.container` and `zope.pluggableauth`, but somehow resulted in `zope.traversing` failing, which is somewhat disturbing (though, the last time it ran successfully was before I updated zope.container and zope.proxy, so there were three version changes). Hopefully it's something local to my machine...I guess I'll look at that too. At least the CPython tests all pass.

```
Error in test testComplexPath (zope.traversing.tests.test_publicationtraverse.TestPublicationTraverser)
Traceback (most recent call last):
  File "//bin/pypy/lib-python/2.7/unittest/case.py", line 329, in run
    testMethod()
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/tests/test_publicationtraverse.py", line 114, in testComplexPath
    proxy = t.traversePath(request, ob, 'foo/../alpha//beta/./bar')
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 104, in traversePath
    ob = self.traverseName(request, ob, name)
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 74, in traverseName
    raise NotFound(ob, name, request)
NotFound: Object: <zope.traversing.tests.test_publicationtraverse.View object at 0x00000001072f83a0>, name: ''



Error in test testPathFound (zope.traversing.tests.test_publicationtraverse.TestPublicationTraverser)
Traceback (most recent call last):
  File "//bin/pypy/lib-python/2.7/unittest/case.py", line 329, in run
    testMethod()
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/tests/test_publicationtraverse.py", line 101, in testPathFound
    proxy = t.traversePath(request, ob, 'foo/bar')
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 104, in traversePath
    ob = self.traverseName(request, ob, name)
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 74, in traverseName
    raise NotFound(ob, name, request)
NotFound: Object: <zope.traversing.tests.test_publicationtraverse.View object at 0x000000010841fa98>, name: 'bar'



Error in test testTraverseRelativeURL (zope.traversing.tests.test_publicationtraverse.TestPublicationTraverser)
Traceback (most recent call last):
  File "//bin/pypy/lib-python/2.7/unittest/case.py", line 329, in run
    testMethod()
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/tests/test_publicationtraverse.py", line 129, in testTraverseRelativeURL
    proxy = t.traverseRelativeURL(request, ob, 'foo/bar')
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 110, in traverseRelativeURL
    ob = self.traversePath(request, ob, path)
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 104, in traversePath
    ob = self.traverseName(request, ob, name)
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/publicationtraverse.py", line 74, in traverseName
    raise NotFound(ob, name, request)
NotFound: Object: <zope.traversing.tests.test_publicationtraverse.View object at 0x000000010846ea68>, name: 'bar'



Error in test testAllAllowed (zope.traversing.tests.test_traverser.RestrictedTraverseTests)
Traceback (most recent call last):
  File "//bin/pypy/lib-python/2.7/unittest/case.py", line 329, in run
    testMethod()
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/tests/test_traverser.py", line 205, in testAllAllowed
    self.assertEquals(tr.traverse(('', 'folder', 'item')), item)
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/adapters.py", line 80, in traverse
    curr = ILocationInfo(self.context).getRoot()
  File "//zopetoolkit/eggs/zope.interface-4.1.2-py2.7.egg/zope/interface/interface.py", line 142, in __call__
    raise TypeError("Could not adapt", obj, self)
TypeError: ('Could not adapt', <zope.traversing.tests.test_traverser.C object at 0x000000010661d830>, <InterfaceClass zope.location.interfaces.ILocationInfo>)



Error in test testItemDenied (zope.traversing.tests.test_traverser.RestrictedTraverseTests)
Traceback (most recent call last):
  File "//bin/pypy/lib-python/2.7/unittest/case.py", line 329, in run
    testMethod()
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/tests/test_traverser.py", line 216, in testItemDenied
    ('', 'folder', 'item'))
  File "//bin/pypy/lib-python/2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "//zopetoolkit/eggs/zope.traversing-4.0.0-py2.7.egg/zope/traversing/adapters.py", line 80, in traverse
    curr = ILocationInfo(self.context).getRoot()
  File "//zopetoolkit/eggs/zope.interface-4.1.2-py2.7.egg/zope/interface/interface.py", line 142, in __call__
    raise TypeError("Could not adapt", obj, self)
TypeError: ('Could not adapt', <zope.traversing.tests.test_traverser.C object at 0x00000001064aa1a8>, <InterfaceClass zope.location.interfaces.ILocationInfo>) 
```

**Comment by tseaver** [comment]
Just guessing: pure-Python proxies cannot lie about their type as the C-based ones do.  That discrepancy might be a factor in those failed adapter lookups.

**Comment by jamadden** [comment]
Interestingly, what seems to be going on with all the TypeErrors is that a security proxied object is getting returned for `__providedBy__`, which then messes up all the dictionary lookups zope.interface does...iterating over it to find individual interfaces returns proxied Interface objects, which can't be found in dictionaries containing the real Interface. The fact that the object itself is proxied seems to be the ultimate but not proximate cause.

It turns out that `zope.interface.interface.Interface` implements `__eq__` in terms of `__name__` and `__module__`, and `__module__` was not being proxied for subclasses of `zope.proxy.PyProxyBase`. 

The change in zopefoundation/zope.security#11 takes care of the issue as a side-effect, although it probably still needs an explicit test case. Any suggestions for where? A "functional" case in `zope.component` (mimicing the existing doctests there)? A low-level Interface based test in `zope.security`? 

Or should `__module__` be special-cased by `zope.proxy` itself?

**Comment by jamadden** [comment]
I got the test case added, but maybe we should just merge this as-is to stop the failing tests and deal with PyPy in another PR? A number of projects need new releases before this will work with PyPy.

**Comment by tseaver** [comment]
Thanks!  Can you enumerate the ones needing release?

**Comment by jamadden** [comment]
I believe the ones that have relevant PRs open and need released are:
- zope.proxy
- zope.security
- zope.session
- zope.pagetemplate
- zope.component

These have already had the relevant PRs merged and just need released:
- zope.testing
- BTrees (optional, enables the zope.catalog doctests to run)

**Comment by tseaver** [comment]
Released:

https://pypi.python.org/pypi/zope.proxy/4.1.6
https://pypi.python.org/pypi/zope.security/4.0.2
https://pypi.python.org/pypi/zope.session/4.1.0
https://pypi.python.org/pypi/zope.pagetemplate/4.2.0
https://pypi.python.org/pypi/zope.testing/4.2.0
https://pypi.python.org/pypi/BTrees/4.1.4

Issues (@jamadden, can you diagnose?):

- The `zope.component` PR is [failing on PyPy3](https://travis-ci.org/zopefoundation/zope.component/builds/64425014).
- The `zope.security` trunk is [failing on PyPy](https://travis-ci.org/zopefoundation/zope.security/builds/65103064) (but passes on PyPy3)

**Comment by jamadden** [comment]
I completely forgot about zopefoundation/zope.publisher#6. 

The zope.component failure (zopefoundation/zope.component#16) is dependent on zopefoundation/zope.security#13.

**Comment by tseaver** [comment]
Released:

- https://pypi.python.org/pypi/zope.publisher/4.2.0

**Comment by jamadden** [comment]
Thank you. The only thing still failing under PyPy is (the released version of) `zope.component`.

**Comment by tseaver** [comment]
Released:

- https://pypi.python.org/pypi/zope.component/4.2.2

**Pull request merged**
