### PR TITLE
Update versions for zope.component 5.

### PR DESCRIPTION
**Pull request by jamadden**
Luckily, the only issues were in test files.

### CODE REVIEW

**Comment by jamadden** [comment]
There's some error in buildout that's preventing this from running here:
```
Getting distribution for 'zc.recipe.egg==2.0.7'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'main'
An error occurred when trying to install /tmp/tmp_avmlx9aget_dist/zc.recipe.egg-2.0.7.tar.gz. Look above this message for any errors that were output by easy_install.
```

I don't have that locally where I am using (an old virtual environment containing) zc.buildout == 2.13.3.

**Comment by jamadden** [comment]
Ahh, Python 3.9 gives a better error message:
```
ImportError: cannot import name 'main' from 'setuptools.command.easy_install' (//python3.9/site-packages/setuptools/command/easy_install.py)
```

It's our old friend setuptools.

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by jamadden** [comment]
Thank you.

**Pull request merged**
