### PR TITLE
Update to newest versions + Test Python 3.8 + drop testing Python 2.

### PR DESCRIPTION
**Pull request by icemac**
We cannot test on Python 2 any more because the current `zope.security` version requires `Sphinx >= 2` for Python 3 but `Sphinx < 2` for Python 2 so there is no version we could pin to which can be used across Python 2 and 3.

### CODE REVIEW

**Comment by jamadden** [comment]
It would be a real shame to drop Python 2 support. It's still early, IMO, and these are stable "foundational" libraries that many slow-moving projects rely on. Perhaps we can adjust `zope.security`. (There are a few things that need done there anyway, like dropping the use of 'Features', some cleanups to the C extension/PURE_PYTHON usage ala what's just been done in zope.interface, etc.)

**Comment by icemac** [comment]
@jamadden I was afraid of this. On the other hand `setuptools` already dropped Python 2 support making the live of maintaining Python 2 support harder.

I created zopefoundation/zope.security#70 to fix zope.security to possibly get back the possibility to pin to a Sphinx version which is allowed by all supported Python versions.

**Comment by mauritsvanrees** [comment]
We could pin versions for Python 2.7 in a separate `[versions:python27]` part. That works with standard buildout and is what [Plone 5.2 is using](https://github.com/plone/buildout.coredev/blob/7c891130fc225a114a83285b1d2f7e5b3dc131ec/versions.cfg#L299) for packages that can only be used on Python 2.7 (like Archetypes) or that need a different pin on 2.7.

Is that an option here?

**Comment by icemac** [comment]
@mauritsvanrees Nice idea, I did not know about this.

**Comment by icemac** [comment]
Managed to keep Python 2 support.

**Comment by jamadden** [comment]
Thank you.

**Pull request merged**
