### PR TITLE
[WIP] Python 3.7 on most current versions.

### PR DESCRIPTION
**Pull request by icemac**
See #28

### CODE REVIEW

**Comment by mgedmin** [comment]
Woo!  Only three packages fail tests on Python 3.7:

- [ ] zope.formlib
- [ ] zope.index
- [ ] zope.publisher

**Comment by mgedmin** [comment]
(zope.copypastemove fails on PyPy3 and I'm not touching that with a 3-meter pole)

**Comment by jamadden** [comment]
> (zope.copypastemove fails on PyPy3 and I'm not touching that with a 3-meter pole)

Only one of the two runs of PyPy3 failed with:

```
Expected nothing
Got:
    Traceback (most recent call last):
      File "/home/travis/virtualenv/pypy3.5-5.8.0/lib-python/3/weakref.py", line 387, in remove
        del self.data[k]
    KeyError: <weakref at 0x000000000265d2e0; dead>
```

That's the GC kicking in at a random time. As for what the actual underlying problem is, who knows, but I bet running PyPy3 again will "fix" it.

**Comment by jamadden** [comment]
The zope.index failures are legit and will take some thought to address; see https://github.com/zopefoundation/zope.index/pull/20

The zope.formlib failure is just a doctest issue having to do with Python 3.7 dropping the trailing `,` in exception strings.

The zope.publisher failure is apparently a change in the way cookies are quoted: https://bugs.python.org/issue991266 Based on that BPO entry, that will probably come out to bite us on a maintenance release of 3.6 as well, so the test probably needs changed to accept either form.

**Comment by icemac** [comment]
No we have failures for the following packages but now for all versions:

- [ ] zope.formlib
- [ ]zope.configuration

**Pull request merged**
