### PR TITLE
Update lxml to Python 3.8b1 compatible version

### PR DESCRIPTION
**Pull request by icemac**

### CODE REVIEW

**Comment by icemac** [comment]
Python 3.8 now successfully builds but there is a strange error in the `zope.traversing` tests.

**Comment by mgedmin** [comment]
Maybe let's [allow 3.8-dev failures](https://docs.travis-ci.com/user/build-matrix/#rows-that-are-allowed-to-fail) for now?

**Comment by icemac** [comment]
Wow, the fix is already on Python 3.8 master, so we do not need to allow it to fail.
@mgedmin Thank you for your investigation.

**Comment by icemac** [comment]
PyPy is so flaky.

**Pull request merged**
